name: Publish Beta Package

on:
  push:
    branches:
      - beta

jobs:
  publish-beta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for branch detection

      - name: Determine Version
        id: version
        run: |
          # Fetch all tags
          git fetch --tags

          # Get the latest tag
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)

          # Append '-beta' to the latest tag
          VERSION="${LATEST_TAG}-beta"

          # Export the version and npm tag
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "NPM_TAG=beta" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Configure NPM Authentication
        run: |
          echo "@bitte-ai:registry=https://registry.npmjs.org/" > ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - name: Publish with pnpm
        run: pnpm publish --access public --tag ${{ env.NPM_TAG }} --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}