name: Publish Package

on:
  push:
    tags:
      - 'v*' # Regular releases (v1.0.0)
      - 'v*-beta.*' # Beta releases (v2.0.0-beta.1)

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for branch detection

      - name: Determine Version and Branch
        id: version_branch
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          # Determine if this is a beta release
          if [[ $VERSION == *"-beta"* ]]; then
            echo "NPM_TAG=beta" >> $GITHUB_ENV
            git checkout react19-beta  # or whatever your beta branch is named
          else
            echo "NPM_TAG=latest" >> $GITHUB_ENV
            git checkout main  # or your stable branch
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Set Version in Package
        run: pnpm version ${{ env.VERSION }} --no-git-tag-version

      - name: Configure NPM Authentication
        run: |
          echo "@bitte-ai:registry=https://registry.npmjs.org/" > ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - name: Publish with pnpm
        run: pnpm publish --access public --tag ${{ env.NPM_TAG }} --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}