name: Publish Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Triggers on version tags like v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Specify the Node.js version you want to use

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Determine Version
        id: determine_version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            # Get the current version from package.json
            CURRENT_VERSION=$(node -p "require('./package.json').version")
            # Increment the pre-release version
            BASE_VERSION=$(echo $CURRENT_VERSION | awk -F- '{print $1}')
            PRERELEASE=$(echo $CURRENT_VERSION | awk -F- '{print $2}')
            PRERELEASE_NUMBER=$(echo $PRERELEASE | awk -F. '{print $NF}')
            NEW_PRERELEASE_NUMBER=$((PRERELEASE_NUMBER + 1))
            NEW_VERSION="$BASE_VERSION-beta-$NEW_PRERELEASE_NUMBER"
            # Configure git to use the GITHUB_TOKEN
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git tag $NEW_VERSION
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} $NEW_VERSION
            VERSION=$NEW_VERSION
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set Version in Package
        run: npm version ${{ env.VERSION }} --no-git-tag-version

      - name: Configure NPM Authentication
        run: |
          echo "@bitte-ai:registry=https://registry.npmjs.org/" > ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - name: Publish with npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false